# Generated by Django 4.1.5 on 2023-01-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('time_auto', models.FloatField(default=0.0)),
                ('cash_account', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.user')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=100)),
                ('time_training', models.CharField(max_length=100)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.user')),
                ('trainer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.trainer')),
            ],
        ),
    ]
